### ISSUE TITLE
MSharp.F7 Performance

### ISSUE THREAD

**Issue by StephenAtGeeks** [Geeksltd/MSharp.Docs#23]
This is far from instant: takes between 3-5 seconds to open the files (depending on the size of the file), and even when all 3 tabs are already open swapping between them takes 2-3 seconds to swap between the tabs.

At the moment this makes the extension unusable, as its faster to just go the file manually. 

Is there anyway we can allocate some time to look for possible ways to improve this?

**Comment by pharzath** [comment]
Yes, But first please let me check it again

**Comment by pharzath** [comment]
### Fixed: Performance issue has been solved. 
So please check it for any other issues.
