### ISSUE TITLE
MSharp.Intellisense - Performance

### ISSUE THREAD

**Issue by StephenAtGeeks** [Geeksltd/MSharp.Docs#24]
I tried out the intellisense extension on one of geeks pretty big application and the dialog box never opened. Was stuck on loading forever. Shown below!

![loadingforever](https://user-images.githubusercontent.com/40687782/46082803-daceab80-c197-11e8-9e82-956b0bc13cf8.PNG)

**Comment by pharzath** [comment]
in large size solutions, unfortunately, we have the performance problem in loading the generated Intellisense file in VS Peeker !!! After user triggers intellisense command in editor (by using [Alt+I] or [Ctrl+.] keys or by selecting the first item of editor context menu ) immediately Intellisense executes "MSharp.exe" with proper arguments ,then a progress bar displayed on top of the peeker and a thread waits until "IntelliSenseTemp.cs" file generated in [..\Website\_M#_TEMP] folder, then automatically peeker loads the file in panel, and Done ! in the Intellisense  we just call MSharp.exe in user requests so I think  Intellisense cannot reduce the performance .
I think "MSharp[.exe]" developers can better help us in this case

**Comment by PaymonK** [comment]
I have now added content variables. If anything else is needed, let me know.

**Comment by StephenAtGeeks** [comment]
Weird issue now. The generated code is completely fine - it takes the controller and properties fine, and if I copy and paste the generated code into a normal C# class inside visual studio the intellisense works fine. However, inside the Peek Definition window in visual studio I still don't get any of the controller intellisense - even though the partial class is correct?

**Comment by PaymonK** [comment]
Try this:

1. Press Alt+i
2. Leave the widget open in VS
3. In the file system, copy the generated temp cs file and add to the project with a different name
4. Open that file, see if intellisense works there

**Comment by StephenAtGeeks** [comment]
Tried this and the intellisense works fine in a seperate C# file - so the generated code is fine! Just weirdly does not work in the widget.

**Comment by PaymonK** [comment]
@pharzath please investigate

**Comment by pharzath** [comment]
OK, I'm working on it to solve the issue

**Comment by pharzath** [comment]
Intellisense VSIX works well now, After reviewing and discussing with Stephen, we concluded that the issue was not related to the Intellisense VSIX, So it seems its better to improve generated code by MSharp.exe

**Comment by StephenAtGeeks** [comment]
Closing this issue.
