### ISSUE TITLE
MSharp.AddNew - No option for Crud

### ISSUE THREAD

**Issue by StephenAtGeeks** [Geeksltd/MSharp.Docs#26]
Hey,

At the moment the AddNew their is no option to create a crud page, like on he old MSharp chrome IDE.

It should have the option to add a crud which will create the view/form/list pages.

**Comment by StephenAtGeeks** [comment]
Update on this: When you create a project using the AddNew, the crud option appears. But when a project is converted to MC# - the crud option is not there.

**Comment by pharzath** [comment]
Can you please give me more information about how you convert your project to MC#, then I can get the better understanding about this issue, or Explain it with a simple project create so I can see the wrong action of the AddNew VSIX.

**Comment by StephenAtGeeks** [comment]
Seems to be fine now, believe I was testing wrong. Closing!
