### ISSUE TITLE
MSharp.GoTo 

### ISSUE THREAD

**Issue by StephenAtGeeks** [Geeksltd/MSharp.Docs#29]
I don't seem to be able to get the context menu to appear on pressing CTRL + . 

The menu appears, but none of the installed extension features are present.

**Comment by pharzath** [comment]
YES, it was a bug. actually  after VS 15.6 update  we have to use new Issue 2 main constructors of SuggestedActionSet class were deprecated, So we have to update the VSIX code to use this only constructor of class with this signatures :
         new SuggestedActionSet(requestedActionCategories.First(), new ISuggestedAction[] { result }) 

So Issue Solved successfully.
