### ISSUE TITLE
MSharp.Colorize - Load up error

### ISSUE THREAD

**Issue by StephenAtGeeks** [Geeksltd/MSharp.Docs#30]
After installing MSharp.Colorize, and trying to open a default M# project, I get an error that reads:

"Not implemented (Exception from HRESULT: 0x0004001 (E_NOTIMPL))"

This then crashed my project.

Loading up standard M# and MC# projects is fine, the only projects that seem to be effected by the crash are projects created from the MSharp.AddNew addon.

2) There's no documentation as to what colours have changed and what they now look like. The only noticeable change I found was a red tinted background on MC# projects.

**Comment by pharzath** [comment]
SOLVED ;)
