### ISSUE TITLE
M# Generation Naming strategies 

### ISSUE THREAD

**Issue by StephenAtGeeks** [Geeksltd/MSharp.Docs#36]
Hey Paymon. Message from Farzad: 

In order to implement the F7 Page file switching by Roslyn, I should create a proper class name from available information such as namespace and class name.

For example when we want to switch to sister file in the "TAndCsAuditPage" page class, then we need the populated controller full class name generated by MSharp, (in the "Controllers" namespace).

So the F7 gets the namespace of current class in addition to the class name plus "Controller" suffix. So the document we should switch has fullClassName something like this :

![capture](https://user-images.githubusercontent.com/40687782/47437862-490b8b80-d7a1-11e8-8f4e-9627933ff578.PNG)

=> AdminContractorsSelectedContractorDetailsTAndCsAuditController

This is not related to File name or Path , So we get it from Roslyn Workspace inside running Visual Studio without new creation.

So if possible please obtain the approval of the naming strategies for the generated Container files.

Another message: 

Another thing if you can check it is, if we can switch to the controller classes by their name (file path in website project) then it will be so faster than we use Roslyn symbol finder , so if Msharp team can grantee that their generated page controller and module controller class file names are same as containing class name , then we can pass a heavy searching easily

**Comment by PaymonK** [comment]
Changed to XML based

**Comment by pharzath** [comment]
So I'll wait to release copy of MSharp, so I can change the F7 VSIX to work with this new version (XML based).

**Comment by pharzath** [comment]
Or it needed I continue working on the current Roslyn version, So if possible please let me know what should I do now, Continue old style developments or Stop it?

**Comment by PaymonK** [comment]
On the latest MSharp nuget package it should generate the Xml. Does it not?

**Comment by pharzath** [comment]
It seems there is a .Net project version mismatch with the new Msharp release and current OneClick UI and Model projects, because after I updated MSharp Nuget reference, then projects cannot build anymore. for example, I get 328 errors of this type :
1>C:\Geeks\OneClick\M#\Model\Enums\NationalInsuranceCategory.cs(5,53,5,63): error CS0234: The type or namespace name 'EntityType' does not exist in the namespace 'MSharp' (are you missing an assembly reference?)
