### ISSUE TITLE
MSharp.AddNew - Error on creation of project

### ISSUE THREAD

**Issue by StephenAtGeeks** [Geeksltd/MSharp.Docs#37]
When I create a new M# project using the extension I get this error (the project does still get created, you just have to manually navigate to it after). See screenshot below.

![2018-10-24 15_31_46-start page - microsoft visual studio administrator](https://user-images.githubusercontent.com/40687782/47438449-61c87100-d7a2-11e8-8955-fdb2e1b91eac.png)

**Comment by pharzath** [comment]
Ok, I'll be working to solve it ASAP

**Comment by pharzath** [comment]
In the time AddNew VSIX was created, new project creation approach was depending on running a batch file after solution(projects) template creates, but it seems now there is no .bat file in the template package any more. (also your testing VSIX version was old ;) )
Anyway, this issue is SOLVE!
