### ISSUE TITLE
MSharp.CodePreview

### ISSUE THREAD

**Issue by StephenAtGeeks** [Geeksltd/MSharp.Docs#40]
Currently, I have MSharp.CodePreview installed, but I cannot see any "Preview generated code..."  button at all?

Am I being blind?

**Comment by pharzath** [comment]
MSharp.Codepreview is designed to show 3 file types (SQL, DAL, Structure) beside of current Entity class that could be generated by MSharp, So there is an item in the text view context menu (first item) with name "Show Generated Code" when you are editing the Model classes.
Currently when I write this for you, the item is there :) , if you do not have this item when editing Model classes (Entities) then please let me know your current VS version (Please be up to date) and if you get any error in output window please send it to me as well.
Hope always your eyes be bright ;)

**Comment by pharzath** [comment]
Another Tip:
In the new VS version, package loading strategies are changed, So after we try to open a solution then it loads VS mandatory packages extension and all external packages are put in a random queue to load, then maybe after 4 to 10 seconds our packages not ready to run! (I know you better than me know this, but it's only my suggestion about this problem for now )

**Comment by pharzath** [comment]
SOLVED
