### ISSUE TITLE
MSharp.AddNew - CRUD Generating wrong

### ISSUE THREAD

**Issue by StephenAtGeeks** [Geeksltd/MSharp.Docs#43]
Currently adding a crud creates the wrong setup.

1) Has a duplicate customer form (screenshot) int he page and module, the form should only be in the module and the page should just be the page.

2) Spaces in the file name - this is a big no, no spaces, please!

Thanks

![2018-10-30 09_39_51-testproject - microsoft visual studio administrator](https://user-images.githubusercontent.com/40687782/47709471-32918400-dc28-11e8-999d-789a61c906e9.png)

**Comment by pharzath** [comment]
1)**Important Note:** Previously, when Paymon requested me to add a new CRUD menu item, then he clearly asked me to add CRUD menu item under Entity and Page file types, So are you sure to remove CRUD menu Item from Page types and what about Entities and modules? (so if it is possible please specify CRUD should be placed under which types? 
2)Bug Fixed: Spaces in all new generated types are approved (Now it completely depends on supporting spaces in MSharp.exe generating command ;) ).
