### ISSUE TITLE
MSharp.F7 - Double up file path when clicking "Module"

### ISSUE THREAD

**Issue by StephenAtGeeks** [Geeksltd/MSharp.Docs#45]
Hey,

When clicking "Module" on F7, it seems to be doubling up part of the file path when searching for the file, causing it to not be found! - See image below.

![f7extension](https://user-images.githubusercontent.com/40687782/48356943-54aaed80-e68f-11e8-8aa8-c18656f37d48.png)

**Comment by pharzath** [comment]
This problem has been solved.
