### ISSUE TITLE
MSharp.GoTo - Expanding functionality 

### ISSUE THREAD

**Issue by StephenAtGeeks** [Geeksltd/MSharp.Docs#46]
Hey!

At the moment the GoTo is just used in #MODEL to go to an entities property.

Can we expand on this? Can we investigate the possibility of using it in M# solutions and being taken to the actual implementation of that, so for example in #UI it will go to the generated code?

We can even expand this further by taking you to M#s implementation of something! 

Thanks

**Comment by pharzath** [comment]
I think it is possible to add this functionality to GOTO VSIX as well, but I need more information how it should navigate (by shortcut-key or a navigation buttons ) also please add this requirement to the ASANA task list to be in our production queue ;)
