### ISSUE TITLE
MSharp.GoTo - File not found errors in Olive projects

### ISSUE THREAD

**Issue by SergioChris** [Geeksltd/MSharp.Docs#51]
Using MSharp.GoTo V3.6.1219 (post merge), F7 extension uninstalled.

Getting File not found errors in various form, this only seems to affect olive projects.

This is from clicking the M# entity button in a generated entities file:
![using f7 to m file](https://user-images.githubusercontent.com/45994586/50299378-59767480-0479-11e9-9447-5e344edc3d7b.png)

This is from pressing F7 from the same file:
![duplicate filename](https://user-images.githubusercontent.com/45994586/50299387-5c716500-0479-11e9-94e9-d94d434397e3.png)

**Comment by iPazooki** [comment]
I have the same issue after updating VS to the latest version `(15.9.4)`

**Comment by pharzath** [comment]
When we display navigation buttons from *msharp-nav.xml* file generated by MSharp.exe , SO : all buttons have been prepared from that XML file ! SO : Only Msharp.exe (Paymon) knows why that button not works
